services:
  server:
    image: server-server:latest
    command: >
      sh -c "npm run start:prod"
    env_file:
      - ./.env
    ports:
      - '7125:7125'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.tomassuxx.ru`)"
      - "traefik.http.routers.server.entrypoints=web"
      - 'traefik.http.routers.server.service=server'
      - "traefik.http.services.server.loadbalancer.server.port=7125"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
