services:
  server:
    container_name: ct_server
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: >
      sh -c "npm run start:prod"
    env_file:
      - ./.env.production
    ports:
      - '${PORT}:${PORT}'
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.constraint-label=traefik_public
        - traefik.http.routers.server-http.rule=Host(`tomassuxx.ru`)
        - traefik.http.routers.server-http.entrypoints=http
        - traefik.http.routers.server-http.middlewares=https-redirect
        - traefik.http.routers.server-https.rule=Host(`tomassuxx.ru`)
        - traefik.http.routers.server-https.entrypoints=https
        - traefik.http.routers.server-https.tls=true
        - traefik.http.routers.server-https.tls.certresolver=le
        - traefik.http.services.server.loadbalancer.server.port=80

networks:
  traefik_public:
    external: true
